global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "autostack-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: "autostack-backend"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

